version: '3.8'

services:
  app_green:
    build: .
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app_green:
    container_name: app_green
    build:
      context: .
    image: nextjs_app:green
    expose:
      - "4001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001"]
      interval: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
    restart: always
