apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: dev
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  type: NodePort
