name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Stop and remove old containers & images
        run: |
          docker-compose down --rmi all --volumes --remove-orphans || true
          docker system prune -f

      - name: Docker Compose Build and Up
        run: |
          docker-compose build --no-cache
          docker-compose up -d
