name: Zero-Downtime Deployment with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        run: |
          # Install Node.js and npm
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs

          # Install Yarn
          npm install -g yarn

      - name: Install PM2 Globally
        run: npm install -g pm2

      - name: Determine Next Deployment Slot
        id: deploy-slot
        run: |
          # Check existing PM2 processes
          EXISTING_APPS=$(pm2 list | grep -E 'test-blue|test-green' || true)
          
          if [[ -z "$EXISTING_APPS" ]]; then
            # First deployment
            echo "DEPLOY_APP=test-blue" >> $GITHUB_ENV
            echo "OLD_APP=" >> $GITHUB_ENV
          elif [[ $(pm2 describe test-blue | grep -c "online") -eq 0 ]]; then
            # Blue slot is available
            echo "DEPLOY_APP=test-blue" >> $GITHUB_ENV
            echo "OLD_APP=test-green" >> $GITHUB_ENV
          else
            # Green slot is available
            echo "DEPLOY_APP=test-green" >> $GITHUB_ENV
            echo "OLD_APP=test-blue" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build Application
        run: |
          yarn build

      - name: Start New PM2 Process
        run: |
          # Generate unique port for new deployment
          PORT=$(python3 -c "import socket; s=socket.socket(); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")
          
          # Start new process
          PM2_ARGS="--name ${{ env.DEPLOY_APP }} --port $PORT"
          pm2 start yarn --interpreter bash $PM2_ARGS -- start

      - name: Wait for New Process to Start
        run: |
          for i in {1..30}; do
            if pm2 describe ${{ env.DEPLOY_APP }} | grep -q "online"; then
              echo "New process started successfully"
              exit 0
            fi
            sleep 5
          done
          echo "Failed to start new process"
          exit 1

      - name: Update Nginx Configuration
        run: |
          # Dynamically update Nginx to route to new process
          NEW_PORT=$(pm2 describe ${{ env.DEPLOY_APP }} | grep "port" | awk '{print $NF}')
          
          # Update Nginx configuration (you'll need to create a script for this)
          /path/to/update-nginx-config.sh ${{ env.DEPLOY_APP }} $NEW_PORT

      - name: Remove Old Process
        if: env.OLD_APP != ''
        run: |
          pm2 delete ${{ env.OLD_APP }} || true
          pm2 save

      - name: Cleanup
        run: |
          pm2 cleanup
          yarn cache clean
