name: Zero-Downtime Deployment with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        run: |
          # Ensure NVM is installed
          if [ ! -d "$HOME/.nvm" ]; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          fi

          # Source NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Install Node.js LTS if not installed
          if ! command -v node &> /dev/null; then
            nvm install --lts
            nvm use --lts
          fi

          # Install Yarn in user's home directory
          if ! command -v yarn &> /dev/null; then
            npm install yarn --no-save --prefix "$HOME/.yarn"
            export PATH="$HOME/.yarn/node_modules/.bin:$PATH"
          fi

      - name: Install Dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # Use local Yarn installation
          export PATH="$HOME/.yarn/node_modules/.bin:$PATH"
          yarn install

      # ... rest of the workflow remains the same
