name: Deploy Next.js with Zero Downtime

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: self-hosted  # Ensure EC2 is set up as a runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Active Container
        id: active
        run: |
          ACTIVE=$(docker ps --format "{{.Names}}" | grep -E 'app_blue|app_green' | head -n 1)
          if [ "$ACTIVE" == "app_blue" ]; then
            echo "TARGET=app_green" >> $GITHUB_ENV
            echo "OLD=app_blue" >> $GITHUB_ENV
          else
            echo "TARGET=app_blue" >> $GITHUB_ENV
            echo "OLD=app_green" >> $GITHUB_ENV
          fi

      - name: Build and Start New Container
        run: |
          docker compose build ${{ env.TARGET }}
          docker compose up -d ${{ env.TARGET }}

      - name: Wait for New Container to be Ready
        run: sleep 10  # Adjust as needed

      - name: Test New Deployment
        run: |
          for i in {1..5}; do
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:4001)
            if [ "$STATUS" -eq 200 ]; then
              echo "Deployment successful!"
              exit 0
            fi
            echo "Waiting for service to start... ($i/5)"
            sleep 5
          done
          echo "Deployment failed!"
          exit 1

      - name: Restart Nginx to Switch Traffic
        run: docker restart nginx_reverse_proxy

      - name: Stop and Remove Old Container
        run: |
          docker stop ${{ env.OLD }} && docker rm ${{ env.OLD }}

      - name: Remove Old Docker Image
        run: |
          IMAGE_ID=$(docker images -q nextjs_app)
          if [ -n "$IMAGE_ID" ]; then
            docker rmi -f $IMAGE_ID
          fi
